name: Run Hello Script

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run hello.sh
        run: ./hello.sh

